version: "3.9"

services:

  group09_mysql:
    image: mysql:8.0
    container_name: group09_mysql
    volumes:
      - ./storage/group09-mysql-data:/var/lib/mysql
    ports:
      - "3307:3306"
    env_file:
      - env
    networks:
      - de_network

networks:
  de_network:
    driver: bridge
    name: de_network