version: "3.9"

services:

  de_mysql:
    image: mysql:8.0
    container_name: de_mysql
    volumes:
      - ./storage/mysql-data:/var/lib/mysql
    ports:
      - "3306:3306"
    env_file:
      - env
    networks:
      - de_network

  de_psql:
    image: postgres:15
    container_name: de_psql
    volumes:
      - ./storage/postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    env_file:
      - env
    networks:
      - de_network

networks:
  de_network:
    driver: bridge
    name: de_network